#!/bin/env node

var fs = require("fs");
var util = require("util");

var cp = require("child_process");
var exec = cp.exec;

var args = process.argv;
if (args.length < 3) {
    console.error("ERR (FATAL): Not enough arguments. Need at least one platform");
    process.exit(1);
}

if (!fs.existsSync("icon.svg")) {
    console.error("ERR (FATAL): Cannot find icon.svg");
    process.exit(1);
}

var platforms = args.slice(2);

process.on("exit", function () {
    console.log("Cleaning up...");

    if (fs.existsSync("icon.png")) {
        fs.unlinkSync("icon.png"); // Generic icon
    }

    platforms.forEach(function (platform, index) {
        var platformSpecificPNG = "icon-" + platform + ".png";
        if (fs.existsSync(platformSpecificPNG)) {
            console.log("Deleting " + platformSpecificPNG + "...");
            fs.unlinkSync(platformSpecificPNG);
        }
    });
});

exportPNGs(platforms);

function exportPNGs(platforms) {
    var started = 0;
    var finished = 0;
    var total = platforms.length + 1; // Length + 1 for generic icon

    console.log(util.format("Exporting generic icon using Inkscape... (%d/%d)", ++started, total));
    exec("inkscape -e icon.png -w 1024 -h 1024 icon.svg", function (error, stdout, stderr) {
        if (error) {
            console.error("ERR (FATAL): " + error);
            process.exit(1);
        }

        if (++finished === total) {
            icon_gen(platforms);
        }
    });

    platforms.forEach(function (platform, index) {
        if (fs.existsSync("icon-" + platform + ".svg")) {
            console.log(util.format("Exporting custom icon for %s using Inkscape... (%d/%d)", platform, ++started, total));
            exec(util.format("inkscape -e icon-%s.png -w 1024 -h 1024 icon-%s.svg", platform, platform), function (error, stdout, stderr) {
                if (error) {
                    console.error("ERR (FATAL): " + error);
                    process.exit(1);
                }

                if (++finished === total) {
                    icon_gen(platforms);
                }
            });
        } else {
            console.log(util.format("Using generic icon for %s... (%d/%d)"), platform, ++started, total);
            if (++finished === total) {
                icon_gen(platforms);
            }
        }
    });
}

function icon_gen(args) {
    console.log("Running icon-gen...");
    exec("icon-gen " + __dirname + "/.. icon.png " + args.toString().replace(/,/g, " "), function (error, stdout, stderr) {
        if (error) {
            console.error("ERR (FATAL): " + error);
            process.exit(1);
        }

        if (stderr) {
            console.error(stderr);
        }
        if (stdout) {
            console.log(stdout);
        }
    });
}